Neste exemplo vamos brincar de vidente, onde temos um array de cartas e vamos tentar prever a proxima carta usando o <b>Scikit-Learn</b>

Vamos importar todas as bibliotecas necessárias

In [43]:
import numpy as np
from sklearn.linear_model import LinearRegression

Agora vamos criar um conjunto de dados com numpy, observe que o array de X usamos o reshape passando -1 para tornar ele bidirecional e 1 para especificar a quantidade de colunas.


In [44]:
x = np.array([1,2,3,4,5]).reshape(-1, 1)
y = np.array([2,4,6,8,10])
print(x)
print(y)

[[1]
 [2]
 [3]
 [4]
 [5]]
[ 2  4  6  8 10]


Agora vamos treinar o nosso modelo de <b>Regressão Linear</b>, e bem simples.

In [45]:
reg = LinearRegression().fit(x, y)


Fazendo uma previsão para um novo valor de X.

In [52]:
new_x = np.array([10, 11, 12]).reshape(-1, 1)
prediction = reg.predict(new_x)
print(new_x)
print(prediction)

[[10]
 [11]
 [12]]
[20. 22. 24.]
